In [1]:
import tensorflow as tf
from tensorflow import keras
import matplotlib.pyplot as plt
%matplotlib inline
import numpy as np

In [26]:
from keras.layers import Dense,Flatten
from keras import Sequential

In [3]:
(X_train,Y_train),(X_test,Y_test) = keras.datasets.mnist.load_data()

In [4]:
print(len(X_train))
print(len(X_test))

60000
10000


In [5]:
X_train[0].shape

(28, 28)

In [6]:
X_train = X_train.reshape(len(X_train),28*28)
X_test = X_test.reshape(len(X_test),28*28)

In [7]:
X_test.shape

(10000, 784)

In [8]:
X_train = X_train/255
X_test = X_test/255

In [9]:
model = Sequential([
    Dense(10 , input_shape = (784,) , activation = 'sigmoid')
])

model.compile(
    optimizer = 'adam',
    loss = 'sparse_categorical_crossentropy',
    metrics = ['accuracy']
)
model.fit(X_train, Y_train, epochs=5, batch_size=32)

Epoch 1/5
1875/1875 [==============================] - 7s 3ms/step - loss: 0.4760 - accuracy: 0.8763
Epoch 2/5
1875/1875 [==============================] - 6s 3ms/step - loss: 0.3042 - accuracy: 0.9154
Epoch 3/5
1875/1875 [==============================] - 6s 3ms/step - loss: 0.2836 - accuracy: 0.9203
Epoch 4/5
1875/1875 [==============================] - 6s 3ms/step - loss: 0.2732 - accuracy: 0.9233
Epoch 5/5
1875/1875 [==============================] - 6s 3ms/step - loss: 0.2668 - accuracy: 0.9257


In [27]:
model0 = Sequential([
    Flatten(input_shape = (28,28)),
    Dense(10 , activation = 'sigmoid')
])

model0.compile(
    optimizer = 'adam',
    loss = 'sparse_categorical_crossentropy',
    metrics = ['accuracy']
)
model0.fit(X_train, Y_train, epochs=5, batch_size=32)

Epoch 1/5


ValueError: in user code:

    File "C:\Users\alisa\.conda\envs\tf_env\lib\site-packages\keras\engine\training.py", line 1051, in train_function  *
        return step_function(self, iterator)
    File "C:\Users\alisa\.conda\envs\tf_env\lib\site-packages\keras\engine\training.py", line 1040, in step_function  **
        outputs = model.distribute_strategy.run(run_step, args=(data,))
    File "C:\Users\alisa\.conda\envs\tf_env\lib\site-packages\keras\engine\training.py", line 1030, in run_step  **
        outputs = model.train_step(data)
    File "C:\Users\alisa\.conda\envs\tf_env\lib\site-packages\keras\engine\training.py", line 889, in train_step
        y_pred = self(x, training=True)
    File "C:\Users\alisa\.conda\envs\tf_env\lib\site-packages\keras\utils\traceback_utils.py", line 67, in error_handler
        raise e.with_traceback(filtered_tb) from None
    File "C:\Users\alisa\.conda\envs\tf_env\lib\site-packages\keras\engine\input_spec.py", line 264, in assert_input_compatibility
        raise ValueError(f'Input {input_index} of layer "{layer_name}" is '

    ValueError: Input 0 of layer "sequential_2" is incompatible with the layer: expected shape=(None, 28, 28), found shape=(32, 784)


In [10]:
model.evaluate(X_test,Y_test)

313/313 [==============================] - 1s 3ms/step - loss: 0.2667 - accuracy: 0.9252


[0.2667491137981415, 0.9251999855041504]

In [11]:
Y_pred = model.predict(X_test)

313/313 [==============================] - 1s 2ms/step


In [16]:
Y_pred = [np.argmax(i) for i in Y_pred]

In [17]:
tf.math.confusion_matrix(labels = Y_test , predictions = Y_pred)

<tf.Tensor: shape=(10, 10), dtype=int32, numpy=
array([[ 964,    0,    1,    2,    0,    4,    6,    2,    1,    0],
       [   0, 1110,    3,    2,    0,    2,    4,    2,   12,    0],
       [   7,    8,  915,   18,    9,    3,   12,   10,   47,    3],
       [   3,    0,   14,  931,    1,   16,    2,   10,   27,    6],
       [   2,    1,    4,    1,  930,    0,   10,    3,   11,   20],
       [  10,    2,    3,   42,   10,  764,   13,    5,   36,    7],
       [  11,    3,    7,    1,    7,   13,  910,    2,    4,    0],
       [   1,    5,   21,    9,    8,    1,    0,  948,    6,   29],
       [   7,    6,    5,   18,    9,   17,    8,   10,  889,    5],
       [  11,    7,    1,    9,   45,    7,    0,   27,   11,  891]])>

In [20]:
model_1 = Sequential([
    Dense(100, input_shape = (784,) , activation = 'relu'),
    Dense(10,activation = 'sigmoid')
])

model_1.compile(
    optimizer = 'adam',
    loss = 'sparse_categorical_crossentropy',
    metrics = ['accuracy']
)
model_1.fit(X_train, Y_train, epochs=5, batch_size=32)

Epoch 1/5
1875/1875 [==============================] - 11s 5ms/step - loss: 0.2697 - accuracy: 0.9231
Epoch 2/5
1875/1875 [==============================] - 8s 4ms/step - loss: 0.1244 - accuracy: 0.9630
Epoch 3/5
1875/1875 [==============================] - 9s 5ms/step - loss: 0.0899 - accuracy: 0.9732
Epoch 4/5
1875/1875 [==============================] - 8s 4ms/step - loss: 0.0668 - accuracy: 0.9797
Epoch 5/5
1875/1875 [==============================] - 11s 6ms/step - loss: 0.0528 - accuracy: 0.9838


In [21]:
model_1.evaluate(X_test,Y_test)

313/313 [==============================] - 1s 3ms/step - loss: 0.0849 - accuracy: 0.9759


[0.0848657488822937, 0.9758999943733215]

In [22]:
Y_pred_1 = model_1.predict(X_test)

313/313 [==============================] - 1s 4ms/step


In [23]:
Y_pred_1 = [np.argmax(i) for i in Y_pred_1]

In [24]:
tf.math.confusion_matrix(Y_test , Y_pred_1)

<tf.Tensor: shape=(10, 10), dtype=int32, numpy=
array([[ 961,    1,    1,    0,    2,    3,    5,    2,    2,    3],
       [   0, 1127,    2,    1,    0,    1,    2,    0,    2,    0],
       [   5,    1, 1000,    6,    1,    0,    2,   12,    5,    0],
       [   0,    0,    1,  977,    0,   16,    0,    8,    4,    4],
       [   0,    0,    5,    0,  969,    0,    2,    0,    2,    4],
       [   2,    1,    0,    4,    2,  876,    1,    1,    4,    1],
       [   3,    2,    0,    1,    9,    4,  938,    0,    1,    0],
       [   0,    4,   11,    1,    1,    1,    0, 1005,    0,    5],
       [   2,    0,    4,    5,   11,    1,    2,    4,  939,    6],
       [   1,    4,    0,    1,   26,    3,    0,    5,    2,  967]])>